apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: snyk-reconciler
spec:
  template:
    spec:
      serviceAccountName: snyk-reconciler
      containers:
      - image: a1doll/k8sreconciler:latest
        name: snyk-reconciler
        resources: {}
        imagePullPolicy: Always
        env:
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: snyk-creds
              key: APITOKEN
        - name: ORGID
          valueFrom:
            secretKeyRef:
              name: snyk-creds
              key: ORGID
        - name: SNYKAPIVERSION
          value: "2023-11-06~beta"
        - name:  SNYKDEBUG
          value: "True"
        - name: DOCKERUSER
          valueFrom:
            secretKeyRef:
              name: snyk-creds
              key: DOCKERUSERNAME
        - name: DOCKERPASSWORD
          valueFrom:
            secretKeyRef:
              name: snyk-creds
              key: DOCKERPASSWORD
      restartPolicy: Never