apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: snyk-reconciler
spec:
  template:
    spec:
      serviceAccountName: snyk-reconciler
      volumes:
        - name: docker-sock
          hostPath:
            path: '/var/run/'
        - name: containerd-images
          hostPath:
            path: '/var/lib/containerd'
      containers:
      - image: a1doll/k8sreconciler:latest
        name: snyk-reconciler
        resources: {}
        imagePullPolicy: Always
        env:
        - name: APIKEY
          value: ""
        - name: ORGID
          value: ""
        - name: SNYKAPIVERSION
          value: "2023-11-06~beta"
        volumeMounts:
          - mountPath: /var/run/
            name: docker-sock
            readOnly: false
          - mountPath: /var/lib/containerd
            name: containerd-images
            readOnly: false
      restartPolicy: Never
status: {}
