apiVersion: v1
kind: Pod
metadata:
  name: test-app
  namespace: default
spec:
  containers:
  - name: backend
    image: doll1av/backend
    imagePullPolicy: IfNotPresent
  - name: frontend
    image: doll1av/frontend
  restartPolicy: Always